### ISSUE TITLE
Why not using cbor_assert everywhere?

### ISSUE THREAD

**Issue by phirsov** [intel/tinycbor#145]
Both cbor_assert macro and standard C assert macro are used in source code with proportion 1:1 roughly. Why? Maybe we should replace assert with cbor_assert for consistency or place a comment explaining this decision?

**Comment by thiagomacieira** [comment]
We use `assert` in cbor.h so that it can be enabled and disabled by the user via the `-DNDEBUG` command-line option. The user may also `#define` it to something different, if they want or have a need to. Note that other public headers should also use `assert`, but the have no current assertions. 

`cbor_assert` is used in all other files, since it won't be removed by the user. It's also defined to be non-empty in `NDEBUG` contexts:

```
#ifdef NDEBUG
#  define cbor_assert(cond)     do { if (!(cond)) unreachable(); } while (0)
#else
#  define cbor_assert(cond)     assert(cond)
#endif
```
