### ISSUE TITLE
CborValue *value = NULL is valid unsigned integer 

### ISSUE THREAD

**Issue by endian-benjamin** [intel/tinycbor#161]
So, the following code returns 0 when `value = NULL` (OS = Zephyr, HW = nRF52).

```
int my_func(CborValue *value) {
	if (!cbor_value_is_unsigned_integer(value) ||
	    cbor_value_get_uint64(value, &crc)) {
		LOG_ERR("Couldn't parse arg");
		return -EINVAL;
	}
	return 0;
}
```

This can't be expected behaviour, right?

**Comment by thiagomacieira** [comment]
Hello @endian-benjamin 

The above code is undefined behaviour. It will crash on other operating systems, due to the definition of `cbor_value_is_unsigned_integer`:
```c
CBOR_INLINE_API bool cbor_value_is_integer(const CborValue *value)
{ return value->type == CborIntegerType; }
CBOR_INLINE_API bool cbor_value_is_unsigned_integer(const CborValue *value)
{ return cbor_value_is_integer(value) && (value->flags & CborIteratorFlag_NegativeInteger) == 0; }
```

As you can see, that dereferences the pointer. So it must not be null. My guess is that in your Zephyr board, the zero address is actually mapped and does read a zero byte, which decodes as an unsigned integer.

You can get the same obscure behaviour on Linux by running:
```sh
setarch --mmap-page-zero ./test
```

Or on Solaris:
```sh
LD_PRELOAD=lib0@0.so ./test
```
